# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waliki', '0006_auto_20171002_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='waliki.Page')),
                ('ref_id', models.CharField(default='', max_length=120, unique=True)),
            ],
            bases=('waliki.page',),
        ),
    ]
