# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-27 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20171030_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('last_updated',)},
        ),
        migrations.AddField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
