# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171227_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='made_public',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
