# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='The Project', max_length=120)),
                ('header_message', models.CharField(default='The Project', max_length=120)),
                ('about', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
