# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lab_message',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='school_message',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_message',
            field=models.CharField(default='The Project', max_length=200),
        ),
    ]
