# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170324_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='lab_message',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='lab_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='school_message',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='school_title',
        ),
    ]
